language: objective-c
osx_image: xcode7.3

script:    
 - xctool -workspace iOS/LTC\ Safety/LTC\ Safety.xcworkspace -scheme LTC\ Safety -sdk iphonesimulator build test 
 - mvn clean package -f LTCSafety/pom.xml
