language: objective-c

matrix:
  include:
    - osx_image: xcode8.2
    - osx_image: xcode8.1
    - osx_image: xcode7.3


#xcode_project: "LTC-Safety/iOS/LTC Safety/LTC Safety.xcodeproj"
xcode_workspace: "iOS/LTC Safety/LTC Safety.xcworkspace"
xcode_scheme: "LTC Safety"

#podfile: LTC-Safety/iOS/LTC Safety/Podfile

xcode_sdk: iphonesimulator
configuration: Debug



#script:    
#    - pwd ; ls ; ls "iOS/LTC Safety"
#    - xcodebuild -workspace "iOS/LTC Safety/LTC Safety.xcworkspace" -list
#    - xcodebuild clean build -sdk iphonesimulator -workspace "iOS/LTC Safety/LTC Safety.xcworkspace" -scheme "LTC SafetyTests" -configuration Debug CODE_SIGNING_REQUIRED=NO
    #- xcodebuild clean build -sdk iphonesimulator -project "iOS/LTC Safety/LTC Safety.xcodeproj" CODE_SIGNING_REQUIRED=NO
