language: java
jdk:
  - oraclejdk7
script: 
  - if [ "${TRAVIS_BRANCH}" == "web-backend" ] ; then mvn clean compile -f LTCSafety/pom.xml ; fi
  - if [ "${TRAVIS_BRANCH}" == "web-backend-build" ] ; then mvn clean package -f LTCSafety/pom.xml ; fi
after_success:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - if [ "${TRAVIS_BRANCH}" == "web-backend" ] ; then git push origin web-backend:web-backend-build ; fi
notifications:
  slack: 
    on_success: change
    on_failure: always
  email: false
