language: objective-c
osx_image: xcode8.2
xcode_project: "LTC-Safety/iOS/LTC Safety/LTC Safety.xcodeproj"
xcode_scheme: "LTC-Safety/iOS/LTC Safety/LTC Safety"
podfile: "LTC-Safety/iOS/LTC Safety/Podfile"
