language: java
jdk:
  - oraclejdk7
script: mvn verify
notifications:
  slack: 
    rooms:
      -'<cmpt371team2>:<dCejYqfn5bhvaeXZImuUmDT0>#buildstatus'
    on_success: always
    on_failure: always
