language: java
jdk:
  - oraclejdk7
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: mvn test -f LTCSafety/pom.xml
notifications:
  slack: 
    rooms:
      -cmpt371team2:<dCejYqfn5bhvaeXZImuUmDT0>
    on_success: always
    on_failure: always
