language: java
jdk:
  - oraclejdk7
script: mvn test -f LTCSafety/pom.xml
after_success:
  if [[ $TRAVIS_BRANCH == 'development' ]]


  fi
notifications:
  slack: 
    cmpt371team2:dCejYqfn5bhvaeXZImuUmDT0
    on_success: change
    on_failure: always
  email: false
