language: java
jdk:
  - oraclejdk7
script: mvn test -f LTCSafety/pom.xml
notifications:
  slack: 
    rooms:
      -cmpt371team2:<dCejYqfn5bhvaeXZImuUmDT0>
    on_success: always
    on_failure: always
