language: java
mvn test -B
jdk:
  - oraclejdk7
notifications:
  slack: 
    rooms:
      -'<cmpt371team2>:<dCejYqfn5bhvaeXZImuUmDT0>#buildstatus'
    on_success: always
    on_failure: always
