matrix:
  include:
    - os: osx
      language: java
    - os: osx
      language: objective-c
      osx_image: xcode8.2
    - os: linux
      language: android
      jdk: oraclejdk8
      sudo: required
      android:
        components:
          #Android SDK Tools
          - platform-tools
          - tools
          #Project BuildTools version
          - build-tools-25.0.2
          #Compile SDK
          - android-25
          #Other components
          - extra-android-support
          - extra-google-m2repository
          - extra-android-m2repository
    
env:
  global:
    # Install timeout in minutes (set to 8 minutes)
    - ADB_INSTALL_TIMEOUT=8

script:
    - chmod +x travis/buildScript.sh
    - travis/buildScript.sh