language: objective-c
osx_image: xcode8.2

script:    
  - chmod +x iOS/build_scripts/script.sh
  - ./iOS/build_scripts/script.sh

after_success: # push to branch 'ios-app-build' to indicate that it compiled successfully (essentially a fastforward merge)
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - if [ "${TRAVIS_BRANCH}" == "ios-app" ] ; then git push origin ios-app:ios-app-build ; fi
